# Generated by Django 6.0.6 on 2026-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imageTitle',
            new_name='image_title',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('LLMOps', 'LLMOps'), ('Full Stack', 'Full Stack'), ('Agents', 'Agents'), ('RAG', 'RAG'), ('Fine-Tuning', 'Fine-Tuning')], default='Full Stack', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True),
        ),
    ]
